spring.application.name=be_do_an_tot_nghiep
server.port=8080
spring.datasource.url=jdbc:mariadb://localhost:3306/do_an_tot_nghiep_cake_store
spring.datasource.username=root
spring.datasource.password=28052004
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vinhdaumoi2805@gmail.com
spring.mail.password=ngoquangvinh2805
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=ZP9LBJeleBIycs5InJt26KXIJBpm1Joae1d1kiaUMUlzbpycDEVBJYKUCIlP6ZUIaZMH4Zake8axRNiUnNZP3g==
jwt.expiration=86400000
